### ISSUE TITLE
Install path is wrong on Arch Linux

### ISSUE THREAD

**Issue by jlindgren90** [ampache-browser/ampache_browser#2]
On Arch Linux, with `cmake -DCMAKE_INSTALL_PREFIX:PATH=<prefix>`, shared libraries are installed to `<prefix>/lib64`.  Ampache should follow the convention of other libraries, which is to use `<prefix>/lib`.

**Comment by jlindgren90** [comment]
This might be the fault of cmake rather than the ampache_browser library itself.

**Comment by openhs** [comment]
CMake (or more precisely its GNUInstallDirs module) is [referring](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/GNUInstallDirs.cmake) to http://www.x86-64.org/documentation/abi.pdf document for using `lib64`.  It describes it in appendix A1.  So this behaviour might be correct.

Unfortunately I'm not that familiar with Arch, but if this is Arch specific I would need a document that I could refer to in order to fill a bug against CMake.  I found only [this](https://wiki.archlinux.org/index.php/Arch_filesystem_hierarchy) which is not much.

**Comment by jlindgren90** [comment]
The FHS[1] treats /usr/lib as the normal place for (native) libraries, with /usr/lib<qual> (i.e. /usr/lib32 or /usr/lib64) as an optional location for "alternate format" libraries.  I think that CMake switches to /usr/lib on a Debian-based system (which follows the FHS).  Possibly it should do the same for Arch.

Arch does have a /usr/lib64 symlink to /usr/lib, so it may not matter much one way or the other.

[1] http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

**Comment by openhs** [comment]
I'll keep it as it is relying on lib64 -> lib symlink.  Most of distros provides it too.
